name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'build.sh'
      - 'src/**'
  pull_request:
    branches: [ "main" ]

env:
  HARBOR_REGISTRY: harbor.arfa.wise-paas.com
  HARBOR_PROJECT: advantech-coe-l2-02
  REPOSITORY_NAME: advantech_coe_l2-02
  VERSION_TAG: v2
  LATEST_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Harbor Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.HARBOR_REGISTRY }}
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.REPOSITORY_NAME }}:${{ env.VERSION_TAG }}
          ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.REPOSITORY_NAME }}:${{ env.LATEST_TAG }}
        cache-from: type=registry,ref=${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.REPOSITORY_NAME }}:buildcache
        cache-to: type=registry,ref=${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.REPOSITORY_NAME }}:buildcache,mode=max

    - name: Confirmation Message
      run: echo "Container image ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.REPOSITORY_NAME }}:${{ env.VERSION_TAG }} successfully built and pushed"
